import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/lib/AuthProvider";
import { ThemeProvider } from "./themeprovider/page";
import { Toaster } from "@/components/ui/toaster"; 
import { FeatureFlagProvider } from "../context/FeatureFlagProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "EFANISH-Learning Beyond Boundaries",
  // description: "Generated by EFANISH",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userRole = "admin";
  return (
    <FeatureFlagProvider userRole={userRole}>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     
      
   
        <AuthProvider >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          </AuthProvider>
          <Toaster />
      
      </body>
    </html>
    </FeatureFlagProvider>
  );
}




