import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/lib/AuthProvider";
import { ThemeProvider } from "./themeprovider/page";
import { Toaster } from "@/components/ui/toaster"; 
import { FeatureFlagProvider } from "../context/FeatureFlagProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NeuroPi-Learning Beyond Boundaries",
  // description: "Generated by NeuroPi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userRole = "admin";
  return (
    <FeatureFlagProvider userRole={userRole}>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     
      
   
        <AuthProvider >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
    <div className="flex flex-col items-center justify-center h-screen text-center px-4 text-lg font-semibold text-gray-800 bg-gradient-to-r from-orange-300 to-red-300 md:hidden">
  <span>Please open in desktop mode for a better experience.</span>
  <div>
  <span> For app, open  </span>
  <a
     href="https://play.google.com/store"
    target="_blank"
    rel="noopener noreferrer"
    className="text-blue-500 underline"
  >
      PlayStore
  </a>
  </div>

</div>


          <div className="hidden md:block">
            {children}
          </div>
          </ThemeProvider>
          </AuthProvider>
          <Toaster />
      
      </body>
    </html>
    </FeatureFlagProvider>
  );
}




